version: '3'

volumes:
  static:
  media:
  pg_data:

services:

  postgres:
    image: postgres:13.10
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - kittygram_network

  backend:
    container_name: kittygram_backend
    image: shepherdblaine/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/mnt/static
      - media:/mnt/media
    depends_on:
      - postgres
    networks:
      - kittygram_network

  frontend:
    container_name: kittygram_frontend
    image: shepherdblaine/kittygram_frontend:latest 
    env_file: .env
    volumes:
      - static:/mnt/static/
    depends_on:
      - backend
    networks:
      - kittygram_network
      
  gateway:
    container_name: kittygram_gateway
    image: shepherdblaine/kittygram_gateway:latest 
    ports:
      - "80:80"
    volumes:
      - static:/mnt/static
      - media:/mnt/media
    depends_on:
      - frontend
    networks:
      - kittygram_network

networks:
  kittygram_network:
    driver: bridge
