server {

  listen 80;
  
  server_tokens off;
  
  index index.html;
  
  location / {
    root /mnt/static/frontend/build;
    try_files $uri $uri /index.html;
  }

  location /media {
    root /mnt/;
    try_files $uri =404;
  }

  location ~ ^/static/(admin|rest_framework) {
    root /mnt/static/backend/;
    try_files $uri =404;
  }
  
  location ~ ^/(api|admin) {
    include proxy_params_common;
    proxy_pass http://backend:8080;
  }

}
