server {
  listen 80;
  
  index index.html;
  
  location / {
    root /mnt/static/build/;
    try_files $uri @fallback_frontend;
  }

  location /media {
    root /mnt/;
    try_files $uri =404;
  }

  location ~ /(api|admin) {
    include proxy_params_common;
    proxy_pass http://backend:8080;
  }
  
  location @fallback_frontend {
    include proxy_params_common;
    proxy_pass http://frontend:8000;
  }

}
